@BaseUrl = http://localhost:3000






### no Dearlers returned in the /categories when app-region is NA



GET {{BaseUrl}}/categories



app-region: NA







###  Dearlers returned in the /categories when app-region is CN



GET {{BaseUrl}}/categories



app-region: CN



